services:
  helloworld:
  image: "testcontainers/helloworld:1.3.0"
  restart: unless-stopped
  ports:
    - "8080:8080"
      # labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.helloworld.rule=Host(`avap.local`) && PathPrefix(`/hello`)"
      #- "traefik.http.routers.helloworld.entrypoints=web"
      #- "traefik.http.services.helloworld.loadbalancer.server.port=8080"
        #- "traefik.http.routers.helloworld.tls=true"

